// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV4Av3mJhmhVPZJvW9mPjX6nzVO3P0z7k',
    appId: '1:771582193833:web:fbd760b6733083dfb1f9b8',
    messagingSenderId: '771582193833',
    projectId: 'zego-cloud-firebase-app',
    authDomain: 'zego-cloud-firebase-app.firebaseapp.com',
    storageBucket: 'zego-cloud-firebase-app.appspot.com',
    measurementId: 'G-Z3MJZJ2YZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4hFJq41jXdEuW3o4JJZiKOk1Z6AKV1Yk',
    appId: '1:771582193833:android:751bf2e18e271805b1f9b8',
    messagingSenderId: '771582193833',
    projectId: 'zego-cloud-firebase-app',
    storageBucket: 'zego-cloud-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJCBwASbaqJtQl_Mwi8MszfskiZvcvwC4',
    appId: '1:771582193833:ios:c2206b9aa473cecab1f9b8',
    messagingSenderId: '771582193833',
    projectId: 'zego-cloud-firebase-app',
    storageBucket: 'zego-cloud-firebase-app.appspot.com',
    iosBundleId: 'com.example.videoCallZegoCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJCBwASbaqJtQl_Mwi8MszfskiZvcvwC4',
    appId: '1:771582193833:ios:c760a2be4c8989efb1f9b8',
    messagingSenderId: '771582193833',
    projectId: 'zego-cloud-firebase-app',
    storageBucket: 'zego-cloud-firebase-app.appspot.com',
    iosBundleId: 'com.example.videoCallZegoCloud.RunnerTests',
  );
}
